name: Build Jar

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and verify with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: davidSauerer/she:latest
#          secrets: |
#            GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}

      # - name: Upload artifact (commented out)
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Package
      #     path: staging
